version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-test
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
